[project]
name = "snowflake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.10.9",
    "dbt-snowflake>=1.10.0",
    "snowflake-connector-python>=3.17.2",
]
